version: "3"
services:
    autocut:
        image: "prod/autocut:18.10.31"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/autocut/src:/home/user/src
            - source:/mnt/src
        command: "python3 /usr/dev/bin/autocut.py --src /mnt/src --dst /mnt/src"
        # command: "sleep 3600"
        user: root
        container_name: "Autcut"

        stdin_open: true
        tty: true

    tests:
        image: "dev/autocut:18.10.31"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/autocut/src:/home/user/src
            - ~/ws/autocut/test:/home/user/test
            - source:/home/user/videoSrc
        command: "pytest -s /home/user/test/"
              #        command: "sleep 3600"
        user: root
        container_name: "AutoCutTest"

        stdin_open: true
        tty: true

    single_run:
        image: "dev/autocut:18.10.31"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/autocut/src:/home/user/src
            - ~/ws/autocut/test:/home/user/test
            - source:/home/user/videoSrc
        command: "python3 /home/user/src/autocut.py --src /home/user/videoSrc --dst /home/user/videoSrc"
        user: root
        container_name: "AutoCutSingleRun"

        stdin_open: true
        tty: true

    debug:
        image: "dev/autocut:18.10.31"
        environment:
            - LOCAL_USER_ID=1000
        volumes:
            - ~/ws/autocut/src:/home/user/src
            - ~/ws/autocut/test:/home/user/test
            - source:/home/user/videoSrc
        command: "/bin/sleep 3600"
        user: root
        container_name: "AutoCutDebug"

        stdin_open: true
        tty: true
volumes:
    source:
        driver: cifs
        driver_opts:
            share: drusus.local/Vault6/src
